/**:
  ros__parameters:
    jnt_names : ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7", "joint8", "joint9", "joint10", "joint11", "joint12", "joint13", "joint14", "joint15", "joint16", "joint17", "joint18", "joint19", "joint20", "joint21", "joint22", "joint23", "joint24", "joint25", "joint26", "joint27", "joint28", "joint29", "joint30", "joint31", "joint32"]  # string[]
    ## optional
    dofs_kp   : [2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0, 2000.0]  # double[]
    dofs_kv   : [ 2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0,  2.0]   # double[]
    #dofs_force_lower : [ 20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0,  20.0]   # double[]
    #dofs_force_upper : [-20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0, -20.0]   # double[]
    #base_init_pos  : [0.0, 0.0, 0.0]      # double[]
    #base_init_quat : [1.0, 0.0, 0.0, 0.0] # double[]

/snake_joint_publisher:
  ros__parameters:
    link_lengh : 0.090     # double [m]     使用するヘビ型ロボットのリンク長 
    timer_period_ms : 50   # int    [msec]
    s_h : 0.0              # double [m]     目標曲線上の先頭部の位置
    psi : 0.0              # double [rad]   捻転角
    radius : 2.0           # double [m]     円弧・螺旋の半径
    d_s_h : 0.5            # double [m/s]   s_hの増減速度
    d_psi : 3.14           # double [rad/s] psiの増減角速度
    radius_threshold : 0.8 # double [m]     常に一定値で半径を変化させると、半径大のときは変化が遅く、半径小のときは速すぎる 
    d_radius_large : 0.5   # double [m/s]   半径の増減速度
    d_radius_small : 0.1   # double [m/s]   
    d_ratio : 0.25         # double [1/s]   歩様変更の移行速度
